# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

# For more details about configuring your Gradle environment:
# https://docs.gradle.org/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle daemon.
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true

# Hadi App Build 18-08-2026

# YE LINE NAYI ADD KAR DO
android.suppressUnsupportedOptionWarnings=RepositoriesMode
